### ISSUE TITLE
Build is not warning free

### ISSUE THREAD

**Issue by sago007** [OpenArena/engine#33]
Currently the compiler emits warnings: https://travis-ci.org/OpenArena/engine/builds/187753304

Warnings in the CI system are unacceptable. 

Code that are incomplete should be "#if 0" (if it will be completed later) or removed (if not).

Problems like the Linux 64 bit version crashing would have been much easier to spot if the code had been warning free.

**Comment by leilei-** [comment]
I use GCC 4.7.2 to do engine work and it's not as warning sensitive as later GCCs i've seen.  Most of the warnings has to do with unused variables as some of the work I did was a partial sandbox commit. I do still try to clean up before I commit as i do find commiting on Git difficult personally

**Comment by sago007** [comment]
I know it is hard but I believe that it is worth the effort. It makes it so much easier to spot that something is wrong.

I especially talked about Travis because it is running gcc 4.6.3 (and should be less aggressive than other compilers). Not later than March the Travis build will change to gcc 4.8.x so it might be more aggressive after that. 
I run gcc 6.2.0 so I get a lot.

**Comment by sago007** [comment]
I have started working through the warnings on https://github.com/OpenArena/engine/tree/fix_warnings

**Comment by sago007** [comment]
As of right now Travis is happy: https://travis-ci.org/OpenArena/engine/builds/340655783
I don't want to keep more than one compiler happy (and that should be the CI compiler).
