### ISSUE TITLE
Moving mouse beyond borders results lag

### ISSUE THREAD

**Issue by NeverMine17** [OpenArena/engine#34]
Moving mouse to the borders of window results lag/crash.
Also in-game mouse not moving with mouse.

**Comment by The-Gig** [comment]
Hello NeverMine17.
Could you please provide some more infos? Which OS? Which OA (engine and gamecode) version? 0.8.8? Nightly builds?
What do you mean with "in-game mouse"? Do to mean the _mouse pointer_ when you are in menus or what?
