### ISSUE TITLE
couldn't exec autoexec.cfg

### ISSUE THREAD

**Issue by suijingfeng** [OpenArena/engine#38]
command line show couldn't exec autoexec.cfg

**Comment by NeonKnightOA** [comment]
Creating a blank file called autoexec.cfg in your homedir/OpenArena/baseoa may work?

**Comment by suijingfeng** [comment]
Yes, It work. but I don't know what it is and what is use for. if no use, may I commit the following code?
Cbuf_ExecuteText(EXEC_NOW, "exec autoexec.cfg\n");
Cbuf_Execute();

**Comment by The-Gig** [comment]
IIRC, default.cfg is a different thing (that contains the default key bindings use at the time of a "clean" install). Autoexec.cfg is indeed an optional _user-defined configuration file_ which will be automatically executed on startup.
