### ISSUE TITLE
.pk3 file download rate slow(no more than 13kb/s) in my ubuntu16.04

### ISSUE THREAD

**Issue by suijingfeng** [OpenArena/engine#42]
![issue1](https://user-images.githubusercontent.com/10341056/35762627-e1f19c8c-08d4-11e8-8694-4790e1362d93.png)

I have downloaded many maps files, but none of the download rate can exceed 13kb/s, I uploaded a video to show the case:
[lowDowloadRate.mp4.zip](https://github.com/OpenArena/engine/files/1691315/lowDowloadRate.mp4.zip)

My OS is Ubuntu16.04, win7 don't have this issue. Onetime when I play OA on WIN7, I find that the map download speed is much faster than my ubuntu, so i try to figure out where the problem is.

It may cause by libcurl 7.35.0 lib. 
As I remove the libcurl-7.35.0 folder from the engine SDL2 codebase, then make it link the system default libcurl (7.47.0). After that, the download rate up to 100+kb/s, sometime i can get 1Mb/s. 

My system default libcurl is installed by  `sudo apt-get install curl`, the following is the returned information.

Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.47.0-1ubuntu2.6).

Integrating latest libcurl can be done in later time.

You can try my code repository( https://github.com/suijingfeng/engine )， to see if the download speed can be improve in ubuntu16.04.

**Comment by sago007** [comment]
For the Windows version I believe that we ship libcurl or compile it with static linking. Problem with that approach is that you really want to be able to update it especially if compiled with SSL support.

Looking at https://curl.haxx.se/libcurl/abi.html it appears that all versions since libcurl 7.16.0 are compatible. 
Apparently it has been so long that Ubuntu does no longer mark the ABI compatibility level. In that case the problem might be as easy as always looking for libcurl.a if neither libcurl.so.3 or libcurl.so.4 is found.

**Comment by sago007** [comment]
The above claim can be tested by setting "cl_cURLLib" to "libcurl.so"

**Comment by The-Gig** [comment]
If I understood correctly, you are using _an ioquake3 fork of your own_, using SDL2, instead of the official OA packages (which use SDL1, IIRC), right?

**Comment by suijingfeng** [comment]
yes, I use the code fork from https://github.com/OpenArena/engine/tree/sdl2, 
but my computer also have openarena installed by both `sudo apt-get install openarena` and compile the source git from https://github.com/OpenArena/engine/tree/master. In either way, the download rate is slow or just can not download .pk3 files at all. By the way, the executable openarena.x86_64 link libcurl.so.4 in my ubuntu16.04.

**Comment by sago007** [comment]
After having tested this. I noted that it worked fine for me on Ubuntu 17.10 as long as I compiled with:
```
make USE_CURL=1
```
This makes me want to try the nightly Windows builds to see if they have trouble too.

**Comment by The-Gig** [comment]
Is the SDL2 engine branch actually "active"? I thought that part was removed from Windows Nightly Builds due to not being really supported, but maybe I don't remember correctly...
