### ISSUE TITLE
WARNING: shader models/players/beret/skin1red in skin models/players/beret/head_red.skin not found

### ISSUE THREAD

**Issue by suijingfeng** [OpenArena/engine#43]
![issue1](https://user-images.githubusercontent.com/10341056/35896868-61c35b90-0bf9-11e8-825d-22fceebebfa7.png)

but I notice that those files seems already existed in .openarena/baseoa/pak2-players.pk3
![issue2](https://user-images.githubusercontent.com/10341056/35896980-e0df23a0-0bf9-11e8-81bb-e3dedf937959.png)

so what's the warning means, how to fix it?

**Comment by leilei-** [comment]
Less engine paranoia.  

The skin's written like that to try and seek available filetypes automatically (TGA>JPG>PCX).  It just can't find the one wihtout the extension and just harmlessly moves on to loading the tga instead. 

I don't like the load of warnings either, but this is not a bug with the engine. It's just a bit too verbose.
