### ISSUE TITLE
Typo in compiling code?

### ISSUE THREAD

**Issue by hokuco** [OpenArena/engine#50]
I got this error when compiling. was this just a typo?

sys_unix.c:(.text+0x1e63): undefined reference to `fesetround'

**Comment by sago007** [comment]
Which compiler? OS?
fesetround is part of the C99 standard.
A lot of compilers do not implement C99 but the most common compilers in the Unix world should support it.

**Comment by hokuco** [comment]
Whoops... I'm no c-lang expert, just saw it fly by in the terminal when I wanted to play with a friend and thought it may be a point of interest.
