### ISSUE TITLE
sudo aptitude build-dep ioquake3 not found

### ISSUE THREAD

**Issue by hokuco** [OpenArena/engine#52]
Am I missing something? using stock ubuntu 16.04 in a vm

**Comment by NeonKnightOA** [comment]
Not a problem regarding OA.
Try rebuilding your /etc/apt/sources.list from a default list.

**Comment by sago007** [comment]
The README should be updated. I tested on a Docker ubuntu:16.04 image.
This works:
```
apt-get update
apt-get install -q -y libgl1-mesa-dev libsdl1.2-dev libvorbis-dev libfreetype6-dev mingw-w64 git libxmp-dev
git clone git://github.com/OpenArena/engine.git
cd engine/
make
```
This is how Travis CI is building OpenArena except that it uses Ubuntu 14:04 and skips xmp.

**Comment by hokuco** [comment]
ok, I'll resolve this, I actually did get this working, sorry to waste your time(although I was missing freetype, thanks)
