### ISSUE TITLE
Make r_slowness platform-agnostic.

### ISSUE THREAD

**Issue by NeonKnightOA** [OpenArena/engine#53]
r_slowness and related are a series of cvars introduced by leilei. [Here's what they do](http://openarena.ws/board/index.php?topic=4535.msg50832#msg50832):

> r_slowness\
r_slowness_cpu\
r_slowness_gpu\
\
should roughly fake the speed of the MHz you set CPU to (based on p2 performance, default is 300)  GPU is much looser and is based on mhz (like 93-96 for Voodoo2) and also scales the slowness by screen resolution.  There's even a synthetic bottleneck.  It won't be practical for play, but may be useful for content production (like for realizing the critical performance choke points in the maps - oa_spirit3 has a BAD one thanks to the portal in the water, for example)\
\
What it really  is, is just a sleep command called every finished backend buffer determined by a bunch of division on numbers of vertices, indices, surface count, etc...  It's much better for nailing low performance that com_maxfps can't reach.\
\
Currently no way to simulate texture thrashing (r_slowness_vram would be such a cvar, notably R_SumOfUsedImages does not function at all - and would have been great for doing this)

Such useful feature for development should be platform-agnostic, since it currently works only in Windows. How can this be achieved?

**Comment by The-Gig** [comment]
Just a side note: IIRC, to use it at the moment, the value to be selected is "4"...

**Comment by leilei-** [comment]
i plan to rip this misfeature out.
