### ISSUE TITLE
directional shrapnel damage

### ISSUE THREAD

**Issue by tecan** [OpenArena/engine#57]
if rocket blows up towards opponent vector say a ground shot directly at them it should spray more damage to make it more realistic as peices of shrapnel and floor would still hit them. also ricashae's would be neat.

**Comment by The-Gig** [comment]
Are you searching for "more realistic" rockets in a game where you can _[note]_ strafe-jump so much to be _faster than rockets?_ ^_^

More seriously... modifying weapons behaviors falls under NOTTODO. In other words, that's stuff for a mod.

Maybe a such modify may end up in baseoa _only if disabled by default_, but then probably it would not even be worth the effort... would people really bother to enable it?

_[note]_ Peple more skilled like me can. I'm not so good to get to 800 ups, except maybe after being pushed by an accelerator pad.

PS: What's "ricashae"?

PPS: For posting "ideas", maybe the best place is the "idea pit" section of OA Forums: http://openarena.ws/board/index.php?board=70.0

**Comment by GraionDilach** [comment]
>PS: What's "ricashae"?

Considering that level of English, I presume the word he tried to look for was "ricochet".

**Comment by tecan** [comment]
this one feature could really enhance gameplay. rocket damage is more deadly on quake3 so you wouldnot notice the rocket damage as much. in openarena its very noticable / annoying to kill them right with rockets.

**Comment by The-Gig** [comment]
I'm sorry, I don't get your last comment. AFAIK, rockets in OA behave exactly the same as in Q3A, there should be no difference.

As said, modifying Q3A weapons behavior falls under "NOTTODO", so they should be working _exactly the same_ right now.
What do you mean that rockets are "more deadly" on quake3? Are they faster? Do they provide more direct hit damage? Do they provide more splash damage? Is the splash damage radius wider?
IIRC, a direct rocket hit should do 100 HP damage, I think you can test it in-game with "/devmap mapname" and then "/g_debugdamage 1".
Are you sure you are comparing "baseq3" and "baseoa" and not some kind of mods?

**Comment by leilei-** [comment]
Not engine stuff.
