### ISSUE TITLE
[Windows binary 2022/03/13 - Win10] The executable doesn't work.

### ISSUE THREAD

**Issue by NeonKnightOA** [OpenArena/engine#75]
I'm getting an error 0xc000007b when opening [the latest nightly binaries](https://files.poulsander.com/~poul19/public_files/oa/dev088/engine_windows_nightly/) in Windows 10. The last binary known to work was the 2019-dated one.

I've downloaded the latest stable SDL2 binaries from [here](https://www.libsdl.org/download-2.0.php). The 64-bit version throws that error, the 32-bit version doesn't open.

**Comment by sago007** [comment]
I tried switching to static linking so SDL2.dll is not needed anymore

Now the sound does not work.

**Comment by NeonKnightOA** [comment]
The latest binary now works, however there's another problem. Closing this.
